### ISSUE TITLE
Adding support for gokrazy

### ISSUE THREAD

**Issue by BrunoTeixeira1996** [TheMightyGit/rssole#28]
Hi,
I am planing on using this in [gokrazy](https://gokrazy.org/) but since this needs a feeds.json is it possible to add a flag in case I dont have the feeds.json at the same location as the binary?

I can do this and do a pull request, just need to understand if thats ok

Thanks!

**Comment by TheMightyGit** [comment]
I've added a `-c <filename>` option to override the config file. You'll have to either build from `main` or wait for the next release.

**Comment by TheMightyGit** [comment]
Thinking about it, it also writes a `readcache.json` file in the current directory - I assume that will also be a problem?

**Comment by BrunoTeixeira1996** [comment]
> I've added a `-c <filename>` option to override the config file. You'll have to either build from `main` or wait for the next release.

Great! Thanks! Btw any plan on next release then? gokrazy currently grabs the latest release



> Thinking about it, it also writes a `readcache.json` file in the current directory - I assume that will also be a problem?

Yes that will because the binary will be in a different location so the best thing here is to have another flag to setup that location.
I think thats the best approach !

**Comment by TheMightyGit** [comment]
`-r` flag added for changing readcache location

**Comment by BrunoTeixeira1996** [comment]
@TheMightyGit any plans on the new release? 
Thanks

**Comment by TheMightyGit** [comment]
`v0.0.9` is now available :)

**Comment by TheMightyGit** [comment]
@BrunoTeixeira1996 Inside the `readcache.json` file is a list of stories you've marked as read. You never need to edit this manually, but it does need to be in a writable location.

**Comment by BrunoTeixeira1996** [comment]
adding to this, I do something that is a hacky way of working with gokrazy on another project of mine
Basicaly I create mandatory folders in `/etc/<project>/` inside gokrazy using the `config.json` and then I copy them using go to the `/perm/`

```go
	if *gokrazyFlag {
		// TODO: It would be better to use move instead of copy
		// copy required folders to /pem
		errAssets := cp.Copy("/etc/waiw/assets", "/perm/home/waiw/assets")
		errTemplates := cp.Copy("/etc/waiw/templates", "/perm/home/waiw/templates")
		if errAssets != nil || errTemplates != nil {
			return err
		}
```
Then every time I need to perform an operation inside the `assets` and `templates` I use the following to get the correct path (`/perm/waiw/`)

```go
	currentPath, err := os.Getwd()
	if err != nil {
		return err
	}
```



> @BrunoTeixeira1996 Inside the `readcache.json` file is a list of stories you've marked as read. You never need to edit this manually, but it does need to be in a writable location.

Yep I understand that. Maybe doing what I explain above fixes my problem but that would be kinda ugly in this repo because this is not intended for gokrazy.
I can still fork this repo and make a local change just for me but what do you think? do you think this could be useful for other people?

**Comment by TheMightyGit** [comment]
@BrunoTeixeira1996 Do you have an in-memory `/tmp` you can use for `readcache.json`? It does mean everything would be marked read on reboot/restart tho.

**Comment by BrunoTeixeira1996** [comment]
> @BrunoTeixeira1996 Do you have an in-memory `/tmp` you can use for `readcache.json`? It does mean everything would be marked unread on reboot/restart tho.

`/perm/home/rssole` is the best location for this because thats permanet data 
the `/tmp` will be erased when reboot/restart

But to be able to copy files to `/perm/home/rssole` I need to modify a bit the code to do that

**Comment by TheMightyGit** [comment]
@BrunoTeixeira1996 Ahh, I think I see. You need the rssole binary itself to do the copying because gokrazy is a minimal environment? I think this is out of scope for rssole, so you will have to fork it for that change.

**Comment by BrunoTeixeira1996** [comment]
> @BrunoTeixeira1996 Ahh, I think I see. You need the rssole binary itself to do the copying because gokrazy is a minimal environment? I think this is out of scope for rssole, so you will have to fork it for that change.

Exacly that , gokrazy is a minimal environment with some special specifications.
Ok Ill fork it and make the change localy and I will not do a pull request since this is out of scope.
Thanks!
