### ISSUE TITLE
Lack of auto-refresh of feed list necessitates feed click or reload of page to get it to update.

### ISSUE THREAD

**Issue by TheMightyGit** [TheMightyGit/rssole#4]
Refresh the whole feedlist at once, or individually?
Also, we know when the next update will get called so maybe it should just be 30s after that?

**Comment by BrunoTeixeira1996** [comment]
like I mentioned in the dupped issue , I think using `<meta http-equiv="refresh" content="3" />` is enough for this to work

**Comment by TheMightyGit** [comment]
htmx allows for much finer grained updates than a full page refresh (which would lose state).
